version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 60910990
      POSTGRES_DB: topicos_db
    ports:
      - "5433:5432"   # Tu máquina:5433 → Contenedor:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 60910990
      DB_NAME: topicos_db
      DB_PORT: 5432   # ⚠️ Internamente sigue siendo 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3001   
    ports:
      - "3001:3001" # Forzar puerto 3001
    volumes:
      - .:/usr/src/app
    command: npm run dev:reset
    restart: always

  gateway:
    build: ../gateway
    depends_on:
      - app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run dev
    restart: always

  mi_frontend:
    build: ../mi_frontend/
    depends_on:
      - gateway
    environment:
      PORT: 5173
    ports:
      - "5173:80"
    #volumes:
      #- ../mi_frontend:/usr/src/app
    #command: npm run dev
    restart: always

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
